USE customer_shopping_behaviour
select * from customer_shopping_behaviour

--Total revenue generated by male vs female customers
SELECT gender, SUM(purchase_amount) AS total_revenue 
FROM customer_shopping_behaviour
GROUP BY gender

--Which customer used a discount but still spend more than a average purchase amount
SELECT customer_id,purchase_amount
FROM customer_shopping_behaviour
WHERE Discount_Applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_shopping_behaviour)
GROUP BY customer_id ,purchase_amount

--Which are the top 5 products with the highest average review rating
SELECT TOP 5 item_purchased ,CAST(AVG(review_rating) AS DECIMAL (10,2))AS Average_Product_rate
FROM customer_shopping_behaviour
GROUP BY item_purchased
ORDER BY Average_Product_rate DESC


--Compare the average purchase amount between standard and express shipping
SELECT shipping_type,AVG(purchase_amount) AS Average_purchase_amount
FROM customer_shopping_behaviour
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type

--Do subscribed members spend more? Compare average Spend and total revenue between subscribers and non subscribers
SELECT subscription_status,
COUNT(customer_id) AS Total_Customer,
CAST(AVG(purchase_amount) AS DECIMAL(10,2)) AS Avg_Spend,
SUM(purchase_amount) AS Total_Revenue
FROM customer_shopping_behaviour
GROUP BY subscription_status
ORDER BY Total_Revenue,Avg_Spend DESC

--which 5 product have the highest percentage of purchase with discount applied
SELECT TOP 5 item_purchased,
SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END )*100 /COUNT(*) AS Discount_rate
FROM customer_shopping_behaviour
GROUP BY item_purchased
ORDER BY Discount_rate DESC

--Segment customers into new,returner and loyel based on their total number of previous purchases and showing count of each segment
WITH customer_type AS(
SELECT customer_id,previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returner'
	ELSE 'Loyal'
    END AS customer_segment
FROM customer_shopping_behaviour
)
SELECT customer_segment,COUNT(*) AS Number_of_Customer
FROM customer_type
GROUP BY customer_segment
ORDER BY Number_of_Customer DESC

--What are the top 3 most purchased product within each category
WITH item_count AS (
SELECT category,item_purchased,
COUNT(customer_id) AS Total_Orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id)DESC) AS Item_Rank
FROM customer_shopping_behaviour
GROUP BY category,item_purchased
)

SELECT Item_Rank,category,item_purchased,Total_Orders
FROM item_count
WHERE Item_Rank <=3

--Are customers Who are repeat buyers(more than 5 previous purchases) also likely to subscribe
SELECT subscription_status,
COUNT(customer_id) AS Repeat_Buyers
FROM customer_shopping_behaviour
WHERE previous_purchases >5
GROUP BY subscription_status
ORDER BY Repeat_Buyers DESC

--What is the Revenue contribution of each age group
SELECT age_group,
SUM(purchase_amount) AS Total_Revenue
FROM customer_shopping_behaviour
GROUP BY age_group
ORDER BY Total_Revenue DESC


--Checking the frequency of purchases and purchase frequency days for each category
SELECT category,frequency_of_purchases,purchase_frequency_days,
COUNT(customer_id) AS Total_customer
FROM customer_shopping_behaviour
WHERE purchase_frequency_days IS NOT NULL
GROUP BY category,frequency_of_purchases,purchase_frequency_days
ORDER BY frequency_of_purchases DESC

